class Car{
    constructor(window,engine,wheel,light){
        this.window=window;
        this.engine=engine;
        this.wheel=wheel;
        this.light=light;
    }
}


const cars=[
    new Car('썬팅','3000cc','알루미늄','할로겐'),
    new Car('노썬팅','1000cc','알루미늄','led'),
    new Car('썬팅','2000cc','스틸','할로겐'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','3500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','2500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','스틸','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','스틸','led'),
    new Car('노썬팅','1500cc','스틸','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','할로겐'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','스틸','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','할로겐'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','2000cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','2500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','3000cc','알루미늄','led'),
    new Car('썬팅','1500cc','스틸','led'),
    new Car('노썬팅','3500cc','알루미늄','할로겐'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','할로겐'),
    new Car('노썬팅','2000cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','스틸','led'),
    new Car('썬팅','2000cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1000cc','스틸','할로겐'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1000cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','스틸','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1000cc','스틸','led'),
    new Car('노썬팅','1000cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','2000cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','3000cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','2000cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','할로겐'),
    new Car('노썬팅','2500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','스틸','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','500cc','알루미늄','led'),
    new Car('노썬팅','2000cc','스틸','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','3000cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),
    new Car('썬팅','1500cc','알루미늄','led'),
    new Car('노썬팅','1500cc','알루미늄','led'),

];





{
const result=cars.filter((student)=>student.engine==="3000cc");
console.log(result);
}